allowedUsers = {
   ["magnusfxp"] = true, ---- staff
   ["scout7ixs"] = true, ---- staff
   ["joaozinw11"] = true, ---- staff
   ["THEKINGDARKSIDER"] = true, ---- staff
   ["sr_anjo338"] = true, ---- staff
   ["eubatinumavelha"] = true, ---- staff
   ["hdhfhfxjbx"] = true, ---- staff
   ["CUZCUZ12900"] = true, ---- staff
   ["panderercc"] = true, ---- staff
   ["paulo215726"] = true, ---- staff
   ["tuntunsahur_891"] = true, ---- staff
   ["tui1392"] = true, ---- staff
   ["graknniu"] = true, ---- staff
   ["sdmplees_01"] = true, ---- staff
   ["khanqd_y8"] = true, ---- staff
   ["biel_tropadagrota"] = true, ---- staff
   ["bypablinho_ofc"] = true, ---- staff
   ["renanqkkd35"] = true, ---- staff
   ["Go_p100"] = true, ---- staff
   ["viros_45ks"] = true, ---- staff
   ["lucas02sjsj"] = true, ---- staff
   ["cleitinho_adm"] = true, ---- staff
   ["Aloysioerick"] = true, ---- staff
   ["carlsinhadaquebrada"] = true, ---- staff
   ["Miguel_kiwi777"] = true, ---- staff
   ["MolChops2013"] = true, ---- staff
   ["lindobrs1"] = true, ---- staff
   ["joao96874"] = true, ---- staff
   ["llenado123456"] = true, ---- staff
   ["smulem_01"] = true, ---- staff
   ["Pedrocamandrake391"] = true, ---- staff
   ["KIRA7KILLAS"] = true, ---- staff
   ["daviricardo25022"] = true, ---- staff
   ["Salazar123xxx2"] = true, ---- staff
   ["errorpro1d"] = true, ---- staff
   ["AOEX_FH"] = true, ---- staff
   ["contasegudariadesv"] = true, ---- staff
   ["zoro_fenix42"] = true, ---- staff
   ["nikz68"] = true, ---- staff
   ["kayro20112p"] = true, ---- staff
   ["emanifesto6q"] = true, ---- staff
   ["Lolyta6662"] = true, ---- staff
   ["Migxzz15"] = true, ---- staff
   ["Rei_SilvaHub9"] = true, ---- staff
}

return allowedUsers